
export const allProducts = [
    // ====== MEN PRODUCTS ======
    {
        id: 1,
        name: "Altecia Tie and Dye Jogger",
        brand: "Altecia",
        price: 999,
        oldPrice: 1999,
        rating: 4,
        reviews: "2.4k",
        image: "/images/mns1.webp",
        images: ["/images/mns1.webp", "/images/tshirt.webp", "/images/mns2.webp"],
        category: "men",
    },
    {
        id: 2,
        name: "Black Solid Casual Shirt",
        brand: "V-Mart",
        price: 459,
        oldPrice: 899,
        reviews: "2.4k",
        rating: 2,
        image: "/images/mns2.webp",
        images: ["/images/mns2.webp", "/images/mns1.webp", "/images/whiteshirt.webp"],
        category: "men",
    },
    {
        id: 3,
        name: "Glito Black Solid Dry-Fit Jacket",
        brand: "V-Mart",
        price: 460,
        reviews: "6.1k",
        oldPrice: 490,
        rating: 5,
        image: "/images/mns3.webp",
        images: ["/images/mns3.webp", "/images/shirt.jpg", "/images/redtshirt.webp"],
        category: "men",
    },
    {
        id: 4,
        name: "Men Checkered Long Sleeve",
        brand: "Bushirt",
        price: 850,
        oldPrice: 1200,
        reviews: "4.7k",
        rating: 5,
        image: "/images/mns4.webp",
        images: ["/images/mns4.webp", "/images/mns1.webp", "/images/whiteshirt.webp"],
        category: "men",
    },
    {
        id: 5,
        name: "GESCO Peach Solid Mandar",
        brand: "GESPO",
        price: 1500,
        oldPrice: 2000,
        reviews: ".4k",
        rating: 4,
        image: "/images/mns5.webp",
        images: ["/images/mns5.webp", "/images/shirt.jpg", "/images/whiteshirt.webp"],
        category: "men",
    },
    {
        id: 6,
        name: "Men Layerr Regular Fit Spread Collar Cotton Shirt",
        brand: "GESPO",
        price: 699,
        oldPrice: 1799,
        reviews: "2.4k",
        rating: 4,
        image: "/images/mns6.webp",
        images: ["/images/mns6.webp", "/images/halftshirt.jpg", "/images/whiteshirt.webp"],
        category: "men",
    },
    {
        id: 7,
        name: "Men long sleeve casual shirt",
        brand: "GESPO",
        price: 990,
        oldPrice: 1999,
        rating: 4.5,
        reviews: "3.8k",
        image: "/images/mns7.webp",
        images: ["/images/mns7.webp", "/images/halftshirt.jpg", "/images/whiteshirt.webp"],
        category: "men",
    },
    {
        id: 8,
        name: "Fit Half Sleeves Colorblocked T-Shirt",
        brand: "GESPO",
        price: 490,
        oldPrice: 1499,
        reviews: "9.8k",
        rating: 3,
        image: "/images/mns8.webp",
        images: ["/images/mns8.webp", "/images/whiteshirt.webp", "/images/whiteshirt.webp"],
        category: "men",
    },

    // ====== WOMEN PRODUCTS ======
    {
        id: 51,
        name: "Cotton Set-Tie & Dye Tracksuit with Insert Pockets",
        brand: "Altecia",
        price: 999,
        oldPrice: 1999,
        rating: 4,
        reviews: "3.8k",
        image: "/images/w1.jpg",
        images: ["/images/w1.jpg", "/images/w2.webp", "/images/w3.webp"],
        category: "women",
    },
    {
        id: 52,
        name: "Siril Poly Silk White & Beige Saree With Blouse Piece",
        brand: "V-Mart",
        price: 459,
        oldPrice: 899,
        rating: 2,
        reviews: "5.8k",
        image: "/images/w2.webp",
        images: ["/images/w2.webp", "/images/w3.webp", "/images/w4.webp"],
        category: "women",
    },
    {
        id: 53,
        name: "VNEED Women Embroidered Rayon Kurta Pant Set",
        brand: "Bushirt",
        price: 699,
        oldPrice: 1290,
        rating: 5,
        reviews: "3.8k",
        image: "/images/w4.webp",
        images: ["/images/w4.webp", "/images/w5.webp", "/images/w6.jpg"],
        category: "women",
    },
    {
        id: 54,
        name: "Deel Band Women Rayon Kurta Pant Dupatta Set",
        brand: "GESPO",
        price: 1490,
        reviews: "1.9k",
        oldPrice: 1999,
        rating: 4,
        image: "/images/w5.webp",
        images: ["/images/w5.webp", "/images/w6.jpg", "/images/w7.webp"],
        category: "women",
    },
    {
        id: 55,
        name: "A-Line Kurti With Sharara & Dupatta",
        brand: "GESPO",
        price: 799,
        reviews: "7.8k",
        oldPrice: 1799,
        rating: 4,
        image: "/images/w6.jpg",
        images: ["/images/w6.jpg", "/images/w7.webp", "/images/w8.webp"],
        category: "women",
    },
    {
        id: 56,
        name: "Buy New Trend Women Black Cotton Blend Top",
        brand: "GESPO",
        price: 990,
        reviews: "1.8k",
        oldPrice: 1999,
        rating: 4.5,
        image: "/images/w7.webp",
        images: ["/images/w7.webp", "/images/w8.jpg", "/images/w1.jpg"],
        category: "women",
    },
    {
        id: 57,
        name: "Glowworld Women Blue Printed Cotton Kurta",
        brand: "GESPO",
        price: 490,
        reviews: "3.8k",
        oldPrice: 1499,
        rating: 3,
        image: "/images/w8.jpg",
        images: ["/images/w8.jpg", "/images/w1.jpg", "/images/w2.webp"],
        category: "women",
    },

    //-----------kids------------
    {
        id: 101,
        name: "Baby Girls Calf Length Casual Dress",
        brand: "Altecia",
        price: 999,
        oldPrice: 1999,
        rating: 4,
        image: "/images/k1.webp",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k1.webp", "/images/k2.webp", "/images/k3.webp"],
    },
    {
        id: 102,
        name: " Girls Below Knee Festive/Wedding Dress",
        brand: "V-Mart",
        price: 399,
        oldPrice: 899,
        rating: 2,
        image: "/images/k2.webp",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k2.webp", "/images/k3.webp", "/images/k4.webp"],
    },
    {
        id: 103,
        name: "Girls Below Knee Party Dress ",
        brand: "V-Mart",
        price: 699,
        oldPrice: 1590,
        rating: 3,
        image: "/images/k3.webp ",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k3.webp", "/images/k5.webp", "/images/k2.webp"],
    },
    {
        id: 104,
        name: "skirt and top set for festivals or weddings",
        brand: "Bushirt",
        price: 850,
        oldPrice: 1200,
        rating: 5,
        image: "/images/k4.webp",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k4.webp", "/images/k2.webp", "/images/k3.webp"],
    },
    {
        id: 105,
        name: "long-sleeve dresses, often layered",
        brand: "GESPO",
        price: 399,
        oldPrice: 799,
        rating: 4,
        image: "/images/k5.webp",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k5.webp", "/images/k7.webp", "/images/k3.webp"],
    },
    {
        id: 106,
        name: " light, airy dresses for hot weather ",
        brand: "GESPO",
        price: 499,
        oldPrice: 899,
        rating: 4,
        image: "/images/k6.webp",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k6.webp", "/images/k4.webp", "/images/k3.webp"],
    },
    {
        id: 107,
        name: " fancy dress for parties or weddings",
        brand: "GESPO",
        price: 690,
        oldPrice: 999,
        rating: 4.5,
        image: "/images/k7.webp", reviews: "3.8k",
        category: "kids",
        images: ["/images/k7.webp", "/images/k8.webp", "/images/k3.webp"],
    },
    {
        id: 108,
        name: "casual, comfy, often with fun prints",
        brand: "GESPO",
        price: 490,
        oldPrice: 1499,
        rating: 3,
        image: "/images/k8.webp",
        reviews: "3.8k",
        category: "kids",
        images: ["/images/k8.webp", "/images/k2.webp", "/images/k5.webp"],
    },

    //----------mobile-------
    {
        id: 201,
        name: "iPhone 15 (128 GB) - Black",
        brand: "Apple",
        price: 49990,
        oldPrice: 69900,
        rating: 5,
        reviews: "2k",
        image: "/images/m1.jpg",
        date: "10 Oct",
        category: "mobile",
        images: ["/images/m1.jpg", "/images/m3.jpg", "/images/m7.webp"],
    },
    {
        id: 202,
        name: "Narzo 80 lite (128 GB) - Blue",
        brand: "Narzo",
        price: 19990,
        oldPrice: 27900,
        rating: 5,
        image: "/images/m3.jpg ",
        reviews: "4.8k",
        date: "19 Nov",
        category: "mobile",
        images: ["/images/m3.jpg", "/images/m1.jpg", "/images/m8.webp"],
    },
    {
        id: 203,
        name: "Sumsung s25 Ultra (512 GB)",
        brand: "Sumsung",
        price: 149990,
        oldPrice: 179990,
        rating: 5,
        image: "/images/m9.webp",
        reviews: "12k",
        date: "29 Oct",
        category: "mobile",
        images: ["/images/m9.webp", "/images/m3.jpg", "/images/m7.webp"],
    },
    {
        id: 204,
        name: "One Plus 1+ (512 GB) - Black",
        brand: "One Plus",
        price: 18900,
        oldPrice: 37990,
        rating: 4,
        image: "/images/m4.jpg",
        reviews: "2k",
        date: "14 Oct",
        category: "mobile",
        images: ["/images/m4.jpg", "/images/m3.jpg", "/images/m7.webp"],

    },
    {
        id: 205,
        name: "Narzo 80 Lite (254 GB ) - Black",
        brand: "realme",
        price: 17990,
        oldPrice: 29999,
        rating: 4,
        image: "/images/m5.jpg",
        reviews: "2k",
        date: "10 Oct",
        category: "mobile",
        images: ["/images/m5.jpg", "/images/m1.jpg", "/images/m7.webp"],
    },
    {
        id: 206,
        name: "IQOO Z10R (128 GB) - Silver",
        brand: "IQOO",
        price: 21990,
        oldPrice: 28990,
        rating: 4,
        image: "/images/m6.jpg",
        reviews: "2.6k",
        date: "28 Oct",
        category: "mobile",
        images: ["/images/m6.webp", "/images/m1.jpg", "/images/m3.jpg"],
    },
    {
        id: 207,
        name: "iPhone 17 Air (1 TB) - Black",
        brand: "iPhone",
        price: 89900,
        oldPrice: 124990,
        rating: 4.5,
        image: "/images/m7.webp",
        reviews: "1.8k",
        date: "17 Dec",
        category: "mobile",
        images: ["/images/m7.webp", "/images/m1.jpg", "/images/m2.jpg"],
    },
    {
        id: 208,
        name: "Galaxy Z fold7 (512 GB) - Grey",
        brand: "Sumsung",
        price: 129990,
        oldPrice: 169900,
        rating: 3,
        image: "/images/m8.webp",
        reviews: "4.5k",
        date: "29 Oct",
        category: "mobile",
        images: ["/images/m8.webp", "/images/m7.webp", "/images/m3.jpg"],
    },

    //-----------laptop----------
    
    {
        id: 251,
        name: "HP , 13th Gen Intel Core i3-1215H 8 GB RAM, and 512 GB SSD, 15.6cm, FHD, MS Office",
        brand: "HP",
        price: 69990,
        oldPrice: 89900,
        rating: 5,
        bought: "3.5k",
        image: "/images/l1.webp",
        date: "10 Oct",
        category: "laptop",
        images: ["/images/l1.webp", "/images/l7.webp", "/images/l3.webp"],
    },
    {
        id: 252,
        name: "Dell Inspiron 15 3530: Typically comes with Intel Core i3 / i5, 8 GB RAM, and 512 GB SSD.",
        brand: "Dell",
        price: 54900,
        oldPrice: 69900,
        rating: 5,
        image: "/images/l2.webp ",
        bought: "4.8k",
        date: "19 Nov",
        category: "laptop",
        images: ["/images/l2.webp", "/images/l7.webp", "/images/l3.webp"],
    },
    {
        id: 253,
        name: "Apple MacBook Air M4: Apple M2 chip, 8 GB or 16 GB RAM, 256 GB / 512 GB SSD.",
        brand: "Apple",
        price: 149990,
        oldPrice: 179990,
        rating: 5,
        image: "/images/l9.webp",
        bought: "12k",
        date: "29 Oct",
        category: "laptop",
        images: ["/images/l9.webp", "/images/l5.webp", "/images/l6.webp"],
    },
    {
        id: 254,
        name: "Lenovo IdeaPad Slim 3: AMD Ryzen 5, 8 GB / 16 GB RAM, 512 GB SSD.",
        brand: "Lenovo",
        price: 58900,
        oldPrice: 87990,
        rating: 4,
        image: "/images/l4.webp",
        bought: "2k",
        date: "14 Oct",
        category: "laptop",
        images: ["/images/l4.webp", "/images/l1.webp", "/images/l2.webp"],
    },
    {
        id: 255,
        name: " Acer Nitro 5 AN517-41-R7FP: Ryzen 5 5600H, RTX 3060, 16GB, 512GB,″ 144 Hz display.",
        brand: "realme",
        price: 69990,
        oldPrice: 89999,
        rating: 4,
        image: "/images/l5.webp",
        bought: "2k",
        date: "10 Oct",
        category: "laptop",
        images: ["/images/l5.webp", "/images/l7.webp", "/images/l3.webp"],
    },
    {
        id: 256,
        name: "Acer Nitro V and Predator / Helios lines have higher-end graphics (RTX 40-/50-series)",
        brand: "Acer",
        price: 79990,
        oldPrice: 98990,
        rating: 4,
        image: "/images/l6.webp",
        bought: "2.6k",
        date: "28 Oct",
        category: "laptop",
        images: ["/images/l6.webp", "/images/l6.webp", "/images/l3.webp"],
    },
    {
        id: 257,
        name: "Apple MacBook Air M2: Apple M2 chip, 8 GB or 16 GB RAM, 256 GB / 512 GB SSD .",
        brand: "Apple",
        price: 89900,
        oldPrice: 124990,
        rating: 4.5,
        image: "/images/l7.webp",
        bought: "1.8k",
        date: "17 Dec",
        category: "laptop",
        images: ["/images/l7.webp", "/images/l4.webp", "/images/l3.webp"],
    },
    {
        id: 258,
        name: "Samsung Galaxy Book4: Intel Core i3 / i5 (13th Gen), 8 GB / 16 GB RAM, 512 GB SSD.",
        brand: "Sumsung",
        price: 129990,
        oldPrice: 169900,
        rating: 4,
        image: "/images/l8.webp",
        bought: "4.5k",
        date: "29 Oct",
        category: "laptop",
        images: ["/images/l8.webp", "/images/l7.webp", "/images/l3.webp"],
    },

    //---------entertainment---------------
    {
        id: 301,
        name: "Handheld Game Console with 400 Classic Games | Portable Retro Video Game Player ",
        brand: "HP",
        price: 1990,
        oldPrice: 4900,
        rating: 5,
        bought: "3.5k",
        image: "/images/e1.webp",
        date: "10 Oct",
        category: "entertainemnt",
        images: ["/images/e1.webp", "/images/e7.webp", "/images/e3.webp"],
    },
    {
        id: 302,
        name: "Crompton Galaxy | Strip Light | 5 Meter | 300 LED | 36W | with in-Built Adaptor",
        brand: "sumsung",
        price: 4900,
        oldPrice: 6900,
        rating: 5,
        image: "/images/e2.webp ",
        bought: "4.8k",
        date: "19 Nov",
        category: "entertainemnt",
        images: ["/images/e2.webp", "/images/e7.webp", "/images/e1.webp"],
    },
    {
        id: 303,
        name: "Boat Smart Watch for Kids, Men, Boys, Girls, and Women, D20 Plus 2025",
        brand: "Boat",
        price: 1490,
        oldPrice: 1790,
        rating: 5,
        image: "/images/e3.webp",
        bought: "12k",
        date: "29 Oct",
        category: "entertainemnt",
        images: ["/images/e3.webp", "/images/e5.webp", "/images/e4.webp"],
    },
    {
        id: 304,
        name: "OnePlus / JBL / boAt Neckband Earphones – wireless Bluetooth earphones",
        brand: "One +",
        price: 1589,
        oldPrice: 7990,
        rating: 4,
        image: "/images/e4.webp",
        bought: "2k",
        date: "14 Oct",
        category: "entertainemnt",
        images: ["/images/e4.webp", "/images/e8.webp", "/images/e3.webp"],
    },
    {
        id: 305,
        name: " Samsung 43-inch Crystal 4K TV – smart TV with OTT support",
        brand: "Sumsung",
        price: 39990,
        oldPrice: 49999,
        rating: 4,
        image: "/images/e5.webp",
        bought: "2.8k",
        date: "10 Oct",
        category: "entertainemnt",
        images: ["/images/e5.webp", "/images/e6.jpg", "/images/e3.webp"],
    },
    {
        id: 306,
        name: "HP M070 Ergonomic Wired Mouse / Optical Engine / Accurate/ 1600 DPI",
        brand: "Hp",
        price: 790,
        oldPrice: 990,
        rating: 4,
        image: "/images/e6.jpg",
        bought: "2.6k",
        date: "28 Oct",
        category: "entertainemnt",
        images: ["/images/e6.jpg", "/images/e8.webp", "/images/e1.webp"],
    },
    {
        id: 307,
        name: "pTron Newly Launched Fusion Bliss 16W Bluetooth Speaker with Wireless Mic, Light",
        brand: "pTron",
        price: 890,
        oldPrice: 1290,
        rating: 4.5,
        image: "/images/e7.webp",
        bought: "1.8k",
        date: "17 Dec",
        category: "entertainemnt",
        images: ["/images/e7.webp", "/images/e3.webp", "/images/e2.webp"],
    },
    {
        id: 308,
        name: "Sony PlayStation 5 Digital Edition (slim) Console Video Game",
        brand: "Sony",
        price: 49990,
        oldPrice: 69900,
        rating: 4,
        image: "/images/e8.webp",
        bought: "4.5k",
        date: "29 Oct",
        category: "entertainemnt",
        images: ["/images/e8.webp", "/images/e6.webp", "/images/e3.webp"],
    },

    //-----------Men Shoes-----------
    {
        id: 401,
        name: "Sports Air Max Ultraboost",
        price: 890,
        oldPrice: 1900,
        rating: 5,
        bought: "2k",
        image: "/images/ms1.webp",
        date: "10 Oct",
        category: "menshoes",
        images: ["/images/ms1.webp", "/images/ms6.webp", "/images/ms3.webp"],
    },
    {
        id: 402,
        name: "Campus Soft Frequence Street Runnig Shoe",
        price: 990,
        oldPrice: 1900,
        rating: 5,
        image: "/images/ms2.webp ",
        bought: "4.8k",
        date: "19 Nov",
        category: "menshoes",
        images: ["/images/ms2.webp", "/images/ms3.webp", "/images/ms7.webp"],
    },
    {
        id: 403,
        name: "Mens Go Run Ekevate Runnnig Shoe",
        price: 1190,
        oldPrice: 1990,
        rating: 5,
        image: "/images/ms3.webp",
        bought: "12k",
        date: "29 Oct",
        category: "menshoes",
        images: ["/images/ms3.webp", "/images/ms6.webp", "/images/ms4.webp"],
    },
    {
        id: 404,
        name: "Campus-Adult Strret Running Shoe",
        price: 699,
        oldPrice: 990,
        rating: 4,
        image: "/images/ms4.webp",
        bought: "2k",
        date: "14 Oct",
        category: "menshoes",
        images: ["/images/ms4.webp", "/images/ms8.webp", "/images/ms5.webp"],
    },
    {
        id: 405,
        name: "Mens Profoam Fuegi Res Running Shoe ",
        price: 2290,
        oldPrice: 4999,
        rating: 4,
        image: "/images/ms5.webp",
        bought: "2k",
        date: "10 Oct",
        category: "menshoes",
        images: ["/images/ms5.webp", "/images/ms3.webp", "/images/ms2.webp"],
    },
    {
        id: 406,
        name: " Mens Skate Smart Sneakers",
        price: 1990,
        oldPrice: 3990,
        rating: 4,
        image: "/images/ms6.webp",
        bought: "2.6k",
        date: "28 Oct",
        category: "menshoes",
        images: ["/images/ms6.webp", "/images/ms8.webp", "/images/ms5.webp"],
    },
    {
        id: 407,
        name: "Cause Shoes For Men | Comfortable",
        price: 2190,
        oldPrice: 3990,
        rating: 4.5,
        image: "/images/ms7.webp",
        bought: "1.8k",
        date: "17 Dec",
        category: "menshoes",
        images: ["/images/ms7.webp", "/images/ms6.webp", "/images/ms1.webp"],
    },
    {
        id: 408,
        name: "Men Lace Up Sneakers Shoes",
        price: 1199,
        oldPrice: 3987,
        rating: 3,
        image: "/images/ms8.webp",
        bought: "4.5k",
        date: "29 Oct",
        category: "menshoes",
        images: ["/images/ms8.webp", "/images/ms7.webp", "/images/ms3.webp"],
    },

    //---------Women Shoes--------
    {
        id: 451,
        name: "Sports Air Max Ultraboost",
        price: 890,
        oldPrice: 1900,
        rating: 5,
        bought: "2k",
        image: "/images/ws1.webp",
        date: "10 Oct",
        category: "womenshoes",
        images: ["/images/ws1.webp", "/images/ws5.webp", "/images/ws3.webp"],
    },
    {
        id: 452,
        name: "Soft Frequence Street Runnig Shoe",
        price: 990,
        oldPrice: 1900,
        rating: 5,
        image: "/images/ws2.webp ",
        bought: "4.8k",
        date: "19 Nov",
        category: "womenshoes",
        images: ["/images/ws2.webp", "/images/ws1.webp", "/images/ws7.webp"],
    },
    {
        id: 453,
        name: "Girl Go Run Ekevate Runnnig Shoe",
        price: 1190,
        oldPrice: 1990,
        rating: 5,
        image: "/images/ws3.webp",
        bought: "12k",
        date: "29 Oct",
        category: "womenshoes",
        images: ["/images/ws3.webp", "/images/ws2.webp", "/images/ws8.webp"],
    },
    {
        id: 454,
        name: " Skechers Go Walk Street Shoe",
        price: 699,
        oldPrice: 990,
        rating: 4,
        image: "/images/ws4.webp",
        bought: "2k",
        date: "14 Oct",
        category: "womenshoes",
        images: ["/images/ws4.webp", "/images/ws6.webp", "/images/ws7.webp"],
    },
    {
        id: 455,
        name: "Adidas Profoam Fuegi Running Shoe ",
        price: 2290,
        oldPrice: 4999,
        rating: 4,
        image: "/images/ws5.webp",
        bought: "2k",
        date: "10 Oct",
        category: "womenshoes",
        images: ["/images/ws5.webp", "/images/ws3.webp", "/images/ws1.webp"],
    },
    {
        id: 456,
        name: "Timberland Courma Girl",
        price: 1990,
        oldPrice: 3990,
        rating: 4,
        image: "/images/ws6.webp",
        bought: "2.6k",
        date: "28 Oct",
        category: "womenshoes",
        images: ["/images/ws6.webp", "/images/ws1.webp", "/images/ws4.webp"],
    },
    {
        id: 457,
        name: "Cause Shoes For Women | Comfortable",
        price: 2190,
        oldPrice: 3990,
        rating: 4.5,
        image: "/images/ws7.webp",
        bought: "1.8k",
        date: "17 Dec",
        category: "womenshoes",
        images: ["/images/ws7.webp", "/images/ws2.webp", "/images/ws5.webp"],
    },
    {
        id: 458,
        name: "Women Vans Classic Slip-On | Formal",
        price: 1199,
        oldPrice: 3987,
        rating: 3,
        image: "/images/ws8.webp",
        bought: "4.5k",
        date: "29 Oct",
        category: "womenshoes",
        images: ["/images/ws8.webp", "/images/ws6.webp", "/images/ws3.webp"],
    },


];